- name: Test API
  hosts: myfortimanagers
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
    script_name: demoscript
  tasks:
    - name: get the script
      fmgr_dvmdb_script:
         method: get
         url_params:
            adom: none
         params:
